name: Python Package

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Install package from wheel
        run: python -m pip install dist/*.whl

      - name: Install test dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Verify import
        run: python -c "import retryxlib; print('retryxlib import successful')"

      - name: Run tests
        run: pytest

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Build and publish to PyPI
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
